---
- name: Register v4l2loopback to modules-load.d
  when: not light
  copy:
    dest: "/etc/modules-load.d/v4l2loopback.conf"
    mode: "644"
    content: |
      v4l2loopback
  become: yes
  notify: Reload v4l2loopback

- name: Configure OAK-D Video Source
  when: not light
  lineinfile:
    path: "/etc/modprobe.d/v4l2loopback.conf"
    create: true
    mode: "644"
    line: 'options v4l2loopback video_nr=20 card_label="OAK-D Video Source" exclusive_caps=1'
  become: yes
  notify: Reload v4l2loopback

- name: Configure udev
  lineinfile:
    path: "/etc/udev/rules.d/80-movidius.rules"
    create: true
    mode: "644"
    line: 'SUBSYSTEM=="usb", ATTRS{idVendor}=="03e7", MODE="0666"'
  become: yes
  notify: Reload udev rules

- name: Disable usb output power limit for Raspberry Pi and Raspberry Pi OS
  shell: raspi-config nonint do_usb_current 0
  become: yes
  when:
    ansible_distribution == "Debian"
