---
- name: Register v4l2loopback to modules-load.d
  copy:
    dest: "/etc/modules-load.d/v4l2loopback.conf"
    mode: "644"
    content: |
      v4l2loopback
  become: yes
  notify: Reload v4l2loopback

- name: Configure OAK-D Video Source
  lineinfile:
    path: "/etc/modprobe.d/v4l2loopback.conf"
    create: true
    mode: "644"
    line: 'options v4l2loopback video_nr=20 card_label="OAK-D Video Source" exclusive_caps=1'
  become: yes
  notify: Reload v4l2loopback

- name: Configure udev
  lineinfile:
    path: "/etc/udev/rules.d/80-movidius.rules"
    create: true
    mode: "644"
    line: 'SUBSYSTEM=="usb", ATTRS{idVendor}=="03e7", MODE="0666"'
  become: yes
  notify: Reload udev rules
