---
- name: Get AKARI type from command line
  hosts: all
  tasks:
    - name: Get AKARI type
      args:
        name: light
      set_fact:
        light: "{{ true if light is defined else false}}"

- name: Configure all hosts
  hosts: all
  roles:
    - common

- name: Configure mainpc
  hosts: mainpc
  roles:
    - oak-d
    - role: dynamixel
      when: not light | bool
    - role: feetech
      when: light | bool
    - m5stack

- name: Write M5
  hosts: mainpc
  roles:
    - arduino

- name: Setup docker
  hosts: mainpc
  tags:
    - docker
  roles:
    - docker

- name: Setup akira
  hosts: mainpc
  tags:
    - akira
  roles:
    - akira
