---
- name: Configure all hosts
  hosts: all
  roles:
    - common

- name: Configure mainpc
  hosts: mainpc
  roles:
    - poetry
    - oak-d
    - dynamixel
    - m5stack

- name: Write M5
  hosts: mainpc
  roles:
    - arduino

- name: Setup docker
  hosts: mainpc
  tags:
    - docker
  vars_prompt:
    - name: akira_docker_credential
      prompt: Enter the Docker API token
  roles:
    - docker
    - docker_credential
