---
- name: Configure all hosts
  hosts: all
  roles:
    - common

- name: Configure mainpc
  hosts: mainpc
  roles:
    - oak-d
    - dynamixel
    - m5stack

- name: Write M5
  hosts: mainpc
  roles:
    - arduino

- name: Setup docker
  hosts: mainpc
  tags:
    - docker
  roles:
    - docker

- name: Setup akira
  hosts: mainpc
  tags:
    - akira
  roles:
    - akira
