swagger: "2.0"
info:
  title: akira_proto/project.proto
  version: version not set
tags:
  - name: ProjectService
  - name: AkariServiceService
  - name: SystemService
consumes:
  - application/json
produces:
  - application/json
paths:
  /projects:
    get:
      operationId: ProjectService_ListProjects
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/akira_protoListProjectsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
        - ProjectService
  /projects/create/git:
    post:
      operationId: ProjectService_CreateProjectFromGit
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/akira_protoProject'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/akira_protoCreateProjectFromGitRequest'
      tags:
        - ProjectService
  /projects/create/local:
    post:
      operationId: ProjectService_CreateLocalProject
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/akira_protoProject'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/akira_protoCreateLocalProjectRequest'
      tags:
        - ProjectService
  /projects/delete:
    post:
      operationId: ProjectService_DeleteProject
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/akira_protoDeleteProjectRequest'
      tags:
        - ProjectService
  /projects/detail:
    get:
      operationId: ProjectService_GetProject
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/akira_protoProject'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: query
          required: false
          type: string
      tags:
        - ProjectService
  /projects/edit:
    post:
      operationId: ProjectService_EditProject
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/akira_protoProject'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/akira_protoEditProjectRequest'
      tags:
        - ProjectService
  /projects/refresh:
    post:
      operationId: ProjectService_RefreshProjects
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties: {}
      tags:
        - ProjectService
  /service-images:
    get:
      operationId: AkariServiceService_ListImages
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/akira_protoListImagesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
        - AkariServiceService
  /service-images/{id}:
    get:
      operationId: AkariServiceService_GetImage
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/akira_protoServiceImage'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
      tags:
        - AkariServiceService
  /services:
    get:
      operationId: AkariServiceService_ListServices
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/akira_protoListServicesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
        - AkariServiceService
    post:
      operationId: AkariServiceService_CreateService
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/akira_protoService'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/akira_protoCreateServiceRequest'
      tags:
        - AkariServiceService
  /services/{id}:
    get:
      operationId: AkariServiceService_GetService
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/akira_protoService'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
      tags:
        - AkariServiceService
  /services/{id}/auto_start:
    post:
      operationId: AkariServiceService_SetAutoStartService
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              autoStart:
                type: boolean
      tags:
        - AkariServiceService
  /services/{id}/edit:
    post:
      operationId: AkariServiceService_EditService
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              description:
                type: string
              displayName:
                type: string
      tags:
        - AkariServiceService
  /services/{id}/logs:
    get:
      operationId: AkariServiceService_GetServiceLog
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/akira_protoGetServiceLogResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
      tags:
        - AkariServiceService
  /services/{id}/open:
    get:
      operationId: AkariServiceService_Open
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/akira_protoOpenResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: apiHostname
          in: query
          required: false
          type: string
      tags:
        - AkariServiceService
  /services/{id}/open_project:
    get:
      operationId: AkariServiceService_OpenProject
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/akira_protoOpenProjectResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: apiHostname
          in: query
          required: false
          type: string
        - name: projectId
          in: query
          required: false
          type: string
      tags:
        - AkariServiceService
  /services/{id}/remove:
    post:
      operationId: AkariServiceService_RemoveService
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
      tags:
        - AkariServiceService
  /services/{id}/start:
    post:
      operationId: AkariServiceService_StartService
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
      tags:
        - AkariServiceService
  /services/{id}/stop:
    post:
      operationId: AkariServiceService_StopService
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              terminate:
                type: boolean
      tags:
        - AkariServiceService
  /services/{id}/terminate:
    post:
      operationId: AkariServiceService_TerminateService
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
      tags:
        - AkariServiceService
  /system/current_time:
    get:
      operationId: SystemService_GetSystemTime
      responses:
        "200":
          description: A successful response.
          schema:
            type: string
            format: date-time
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
        - SystemService
  /templates:
    get:
      operationId: ProjectService_ListTemplates
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/akira_protoListTemplatesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
        - ProjectService
definitions:
  akira_protoCreateLocalProjectRequest:
    type: object
    properties:
      dirname:
        type: string
      manifest:
        $ref: '#/definitions/akira_protoProjectManifest'
      templateId:
        type: string
  akira_protoCreateProjectFromGitRequest:
    type: object
    properties:
      branch:
        type: string
      dirname:
        type: string
      gitUrl:
        type: string
  akira_protoCreateServiceRequest:
    type: object
    properties:
      description:
        type: string
      displayName:
        type: string
      imageId:
        type: string
  akira_protoDeleteProjectRequest:
    type: object
    properties:
      id:
        type: string
  akira_protoEditProjectRequest:
    type: object
    properties:
      id:
        type: string
      manifest:
        $ref: '#/definitions/akira_protoProjectManifest'
  akira_protoGetServiceLogResponse:
    type: object
    properties:
      logs:
        type: string
      stderr:
        type: string
      stdout:
        type: string
  akira_protoListImagesResponse:
    type: object
    properties:
      images:
        type: array
        items:
          $ref: '#/definitions/akira_protoServiceImage'
  akira_protoListProjectsResponse:
    type: object
    properties:
      projects:
        type: array
        items:
          $ref: '#/definitions/akira_protoProject'
  akira_protoListServicesResponse:
    type: object
    properties:
      services:
        type: array
        items:
          $ref: '#/definitions/akira_protoService'
  akira_protoListTemplatesResponse:
    type: object
    properties:
      templates:
        type: array
        items:
          $ref: '#/definitions/akira_protoTemplate'
  akira_protoOpenProjectResponse:
    type: object
    properties:
      url:
        type: string
  akira_protoOpenResponse:
    type: object
    properties:
      url:
        type: string
  akira_protoProject:
    type: object
    properties:
      id:
        type: string
      manifest:
        $ref: '#/definitions/akira_protoProjectManifest'
      path:
        type: string
  akira_protoProjectManifest:
    type: object
    properties:
      author:
        type: string
      description:
        type: string
      name:
        type: string
      url:
        type: string
  akira_protoService:
    type: object
    properties:
      autoStart:
        type: boolean
      capabilities:
        type: array
        items:
          type: string
      description:
        type: string
      displayName:
        type: string
      id:
        type: string
      image:
        $ref: '#/definitions/akira_protoServiceImage'
      state:
        $ref: '#/definitions/akira_protoServiceState'
      type:
        $ref: '#/definitions/akira_protoServiceType'
  akira_protoServiceImage:
    type: object
    properties:
      capabilities:
        type: array
        items:
          type: string
      description:
        type: string
      displayName:
        type: string
      id:
        type: string
      name:
        type: string
      version:
        type: string
  akira_protoServiceState:
    type: string
    enum:
      - TERMINATED
      - STARTING
      - RUNNING
      - STOPPING
      - ERROR
      - STOPPED
    default: TERMINATED
  akira_protoServiceType:
    type: string
    enum:
      - USER
      - SYSTEM
    default: USER
  akira_protoTemplate:
    type: object
    properties:
      author:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      tags:
        type: array
        items:
          type: string
      url:
        type: string
      version:
        type: string
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      details:
        type: array
        items:
          $ref: '#/definitions/protobufAny'
      message:
        type: string
