swagger: "2.0"
info:
  title: akira_proto/project.proto
  version: version not set
tags:
  - name: ProjectService
  - name: AkariServiceService
  - name: SystemService
consumes:
  - application/json
produces:
  - application/json
paths:
  /projects:
    get:
      operationId: ProjectService_ListProjects
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/akira_protoListProjectsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
        - ProjectService
    post:
      operationId: ProjectService_CreateProject
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/akira_protoProject'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/akira_protoCreateProjectRequest'
      tags:
        - ProjectService
  /projects/detail:
    get:
      operationId: ProjectService_GetProject
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/akira_protoProject'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: query
          required: false
          type: string
      tags:
        - ProjectService
  /service/launch/jupyter:
    post:
      operationId: AkariServiceService_LaunchJupyterService
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/akira_protoServiceInstance'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/akira_protoLaunchJupyterServiceRequest'
      tags:
        - AkariServiceService
  /services/instances:
    get:
      operationId: AkariServiceService_ListInstances
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/akira_protoListInstancesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
        - AkariServiceService
  /services/instances/{id}:
    get:
      operationId: AkariServiceService_GetInstance
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/akira_protoServiceInstance'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
      tags:
        - AkariServiceService
  /services/instances/{id}/terminate:
    get:
      operationId: AkariServiceService_TerminateInstance
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
      tags:
        - AkariServiceService
  /system/current_time:
    get:
      operationId: SystemService_GetSystemTime
      responses:
        "200":
          description: A successful response.
          schema:
            type: string
            format: date-time
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
        - SystemService
  /templates:
    get:
      operationId: ProjectService_ListTemplates
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/akira_protoListTemplatesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
        - ProjectService
definitions:
  akira_protoCreateProjectRequest:
    type: object
    properties:
      manifest:
        $ref: '#/definitions/akira_protoProjectManifest'
      name:
        type: string
      templateId:
        type: string
  akira_protoLaunchJupyterServiceRequest:
    type: object
    properties:
      projectId:
        type: string
  akira_protoListInstancesResponse:
    type: object
    properties:
      instances:
        type: array
        items:
          $ref: '#/definitions/akira_protoServiceInstance'
  akira_protoListProjectsResponse:
    type: object
    properties:
      projects:
        type: array
        items:
          $ref: '#/definitions/akira_protoProject'
  akira_protoListTemplatesResponse:
    type: object
    properties:
      templates:
        type: array
        items:
          $ref: '#/definitions/akira_protoTemplate'
  akira_protoProject:
    type: object
    properties:
      id:
        type: string
      manifest:
        $ref: '#/definitions/akira_protoProjectManifest'
      path:
        type: string
  akira_protoProjectManifest:
    type: object
    properties:
      author:
        type: string
      description:
        type: string
      name:
        type: string
      url:
        type: string
  akira_protoServiceInstance:
    type: object
    properties:
      description:
        type: string
      id:
        type: string
      name:
        type: string
      serviceAddress:
        type: string
      status:
        $ref: '#/definitions/akira_protoServiceStatus'
  akira_protoServiceStatus:
    type: string
    enum:
      - CREATED
      - STARTING
      - RUNNING
      - STOPPING
      - ERROR
      - COMPLETED
    default: CREATED
  akira_protoTemplate:
    type: object
    properties:
      author:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      tags:
        type: array
        items:
          type: string
      url:
        type: string
      version:
        type: string
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      details:
        type: array
        items:
          $ref: '#/definitions/protobufAny'
      message:
        type: string
