[tool.pysen]
version = "0.11"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = true
mypy_preset = "strict"
line_length = 88
py_version = "py310"
mypy_ignore_packages = ["akari_proto.*"]

[[tool.pysen.lint.mypy_targets]]
  paths = [
    "internal/akari_rpc_server/akari_rpc_server/",
    "internal/akira_controller_server/akira_controller_server/",
    "sdk/akari_client/akari_client",
    "sdk/akari_client/tests/",
    "sdk/akari_proto/akari_proto/",
    "sdk/akari_proto/tests/",
    "tools/python",
  ]

[tool.pysen.lint.source]
  includes = [
    "internal/",
    "sdk/",
    "tools/",
    "samples/",
  ]
  excludes = [
    "internal/akira_services/jupyter_lab/jupyter_lab_config.py",
  ]
  exclude_globs = [
    "sdk/akari_proto/akari_proto/*pb2*",
  ]
