[tool.pysen]
version = "0.10"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = true
mypy_preset = "strict"
line_length = 88
py_version = "py38"
[[tool.pysen.lint.mypy_targets]]
  paths = [
    "samples/akari_sample/script",
    "samples/depthai_sample/face_detection",
    "samples/depthai_sample/object_recognition",
    "samples/m5serial_sample/",
    "sdk/akari_controller/src/akari_controller",
    "sdk/depthai_uvc",
    "tools/python",
  ]
[tool.pysen.lint.source]
  includes = ["src/","tools/"]

