version: "3.7"
services:
  jupyter_lab:
    build:
      context: ../../
      dockerfile: internal/akira_services/jupyter_lab/Dockerfile
    image: akarirobot/akira-jupyter-service:v1
    command: exit 1
