---
- name: Install apt packages
  apt:
    pkg:
      - arduino
  become: true

- name: Install pip packages
  pip:
    name: platformio
  become: true

- name: Copy platformio workspace
  synchronize:
    src: "{{ role_path }}/files/arduino/"
    dest: "{{ ansible_env.HOME }}/arduino/"
    checksum: true
    times: false
  register: upload_workspace

- name: Upload app to M5Stack
  shell: platformio run --target=upload
  args:
    chdir: "{{ ansible_env.HOME }}/arduino/"
  when: upload_workspace.changed
