---
- name: Install apt packages
  apt:
    pkg:
      - curl
      - git
      - libudev-dev
      - python-is-python3
      - python3-pip
      - ssh
      - v4l2loopback-dkms
  become: true

- name: Add user to dialout
  user:
    name: '{{ ansible_user }}'
    groups: dialout
    append: yes
  become: true
