name: 'Build akira images on arm'
description: 'Build akira images on arm'
inputs:
  compose-path:
    description: 'A path to docker-compose file'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Build and push images for arm
      run: |
        source internal/docker/env.sh
        docker compose -f ${{ inputs.compose-path }} build
        docker compose -f ${{ inputs.compose-path }} push
      shell: bash
      env:
        AKIRA_IMAGE_TAG: v1-arm
  with:
    platforms: linux/arm64
