---
- name: Enable serial port(hw) on Raspberry Pi
  shell: raspi-config nonint do_serial_hw 2
  become: yes

- name: Enable hardware serial port(cons) on Raspberry Pi
  shell: raspi-config nonint do_serial_cons 2
  become: yes

- name: Change permissions of serial port
  file:
    path: /dev/serial0
    mode: "0666"
  become: yes

