name: 'Build akira images'
description: 'Build akira images'
inputs:
  compose-path:
    description: 'A path to docker-compose file'
    required: true
  dryrun:
    description: 'Do not push images if the value is set'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Build images
      run: |
        source internal/docker/env.sh
        docker compose -f ${{ inputs.compose-path }} build
      shell: bash
      env:
        AKIRA_IMAGE_TAG: v1
    - name: Push images
      run: |
        source internal/docker/env.sh
        docker compose -f ${{ inputs.compose-path }} push
      shell: bash
      if: ${{ ! fromJson(inputs.dryrun) }}
      env:
        AKIRA_IMAGE_TAG: v1
