name: 'Build akira images'
description: 'Build akira images'
inputs:
  compose-path:
    description: 'A path to docker-compose file'
    required: true
  docker-tag:
    description: 'Docker tag name'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Build and push images
      run: |
        source internal/docker/env.sh
        docker compose -f ${{ inputs.compose-path }} build
        docker compose -f ${{ inputs.compose-path }} push
      shell: bash
      env:
        AKIRA_IMAGE_TAG: docker-tag
