version: "3.7"
services:
  daemon:
    image: akarirobot/akira-daemon:${AKIRA_IMAGE_TAG}
    volumes:
      - type: bind
        source: /etc/akira
        target: /etc/akira
        read_only: true
      - type: bind
        source: ${AKIRA_PROJECT_DIR:?You need to run `source env.sh`}
        target: ${AKIRA_PROJECT_DIR:?You need to run `source env.sh`}
      - type: bind
        source: /var/lib/akira
        target: /var/lib/akira
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    environment:
      HOST_UID: ${HOST_UID:?You need to run `source env.sh`}
      HOST_GID: ${HOST_GID:?You need to run `source env.sh`}
      DOCKER_GID: ${DOCKER_GID:?You need to run `source env.sh`}
      AKIRA_PROJECT_DIR: ${AKIRA_PROJECT_DIR:?You need to run `source env.sh`}
      AKIRA_ETC_DIR: /etc/akira
      AKIRA_VAR_DIR: /var/lib/akira
  gateway:
    image: akarirobot/akira-gateway:${AKIRA_IMAGE_TAG}
    environment:
      AKIRA_DAEMON_ENDPOINT: daemon:30001
    ports:
      - 8080:8080
