# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akari_proto/joint_controller.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"akari_proto/joint_controller.proto\x12\x0b\x61kari_proto\x1a\x1bgoogle/protobuf/empty.proto\"5\n\x14GetJointNameResponse\x12\x1d\n\njoint_name\x18\x01 \x01(\tR\tjointName\"3\n\x17GetServoEnabledResponse\x12\x18\n\x07\x65nabled\x18\x01 \x01(\x08R\x07\x65nabled\"2\n\x16SetServoEnabledRequest\x12\x18\n\x07\x65nabled\x18\x01 \x01(\x08R\x07\x65nabled\"A\n\x1dSetProfileAccelerationRequest\x12 \n\x0crad_per_sec2\x18\x01 \x01(\x02R\nradPerSec2\";\n\x19SetProfileVelocityRequest\x12\x1e\n\x0brad_per_sec\x18\x01 \x01(\x02R\tradPerSec\"*\n\x16SetGoalPositionRequest\x12\x10\n\x03rad\x18\x01 \x01(\x02R\x03rad\".\n\x1aGetPresentPositionResponse\x12\x10\n\x03rad\x18\x01 \x01(\x02R\x03rad2\xdf\x04\n\x16JointControllerService\x12I\n\x0cGetJointName\x12\x16.google.protobuf.Empty\x1a!.akari_proto.GetJointNameResponse\x12O\n\x0fGetServoEnabled\x12\x16.google.protobuf.Empty\x1a$.akari_proto.GetServoEnabledResponse\x12N\n\x0fSetServoEnabled\x12#.akari_proto.SetServoEnabledRequest\x1a\x16.google.protobuf.Empty\x12\\\n\x16SetProfileAcceleration\x12*.akari_proto.SetProfileAccelerationRequest\x1a\x16.google.protobuf.Empty\x12T\n\x12SetProfileVelocity\x12&.akari_proto.SetProfileVelocityRequest\x1a\x16.google.protobuf.Empty\x12N\n\x0fSetGoalPosition\x12#.akari_proto.SetGoalPositionRequest\x1a\x16.google.protobuf.Empty\x12U\n\x12GetPresentPosition\x12\x16.google.protobuf.Empty\x1a\'.akari_proto.GetPresentPositionResponseb\x06proto3')



_GETJOINTNAMERESPONSE = DESCRIPTOR.message_types_by_name['GetJointNameResponse']
_GETSERVOENABLEDRESPONSE = DESCRIPTOR.message_types_by_name['GetServoEnabledResponse']
_SETSERVOENABLEDREQUEST = DESCRIPTOR.message_types_by_name['SetServoEnabledRequest']
_SETPROFILEACCELERATIONREQUEST = DESCRIPTOR.message_types_by_name['SetProfileAccelerationRequest']
_SETPROFILEVELOCITYREQUEST = DESCRIPTOR.message_types_by_name['SetProfileVelocityRequest']
_SETGOALPOSITIONREQUEST = DESCRIPTOR.message_types_by_name['SetGoalPositionRequest']
_GETPRESENTPOSITIONRESPONSE = DESCRIPTOR.message_types_by_name['GetPresentPositionResponse']
GetJointNameResponse = _reflection.GeneratedProtocolMessageType('GetJointNameResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETJOINTNAMERESPONSE,
  '__module__' : 'akari_proto.joint_controller_pb2'
  # @@protoc_insertion_point(class_scope:akari_proto.GetJointNameResponse)
  })
_sym_db.RegisterMessage(GetJointNameResponse)

GetServoEnabledResponse = _reflection.GeneratedProtocolMessageType('GetServoEnabledResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSERVOENABLEDRESPONSE,
  '__module__' : 'akari_proto.joint_controller_pb2'
  # @@protoc_insertion_point(class_scope:akari_proto.GetServoEnabledResponse)
  })
_sym_db.RegisterMessage(GetServoEnabledResponse)

SetServoEnabledRequest = _reflection.GeneratedProtocolMessageType('SetServoEnabledRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETSERVOENABLEDREQUEST,
  '__module__' : 'akari_proto.joint_controller_pb2'
  # @@protoc_insertion_point(class_scope:akari_proto.SetServoEnabledRequest)
  })
_sym_db.RegisterMessage(SetServoEnabledRequest)

SetProfileAccelerationRequest = _reflection.GeneratedProtocolMessageType('SetProfileAccelerationRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETPROFILEACCELERATIONREQUEST,
  '__module__' : 'akari_proto.joint_controller_pb2'
  # @@protoc_insertion_point(class_scope:akari_proto.SetProfileAccelerationRequest)
  })
_sym_db.RegisterMessage(SetProfileAccelerationRequest)

SetProfileVelocityRequest = _reflection.GeneratedProtocolMessageType('SetProfileVelocityRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETPROFILEVELOCITYREQUEST,
  '__module__' : 'akari_proto.joint_controller_pb2'
  # @@protoc_insertion_point(class_scope:akari_proto.SetProfileVelocityRequest)
  })
_sym_db.RegisterMessage(SetProfileVelocityRequest)

SetGoalPositionRequest = _reflection.GeneratedProtocolMessageType('SetGoalPositionRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETGOALPOSITIONREQUEST,
  '__module__' : 'akari_proto.joint_controller_pb2'
  # @@protoc_insertion_point(class_scope:akari_proto.SetGoalPositionRequest)
  })
_sym_db.RegisterMessage(SetGoalPositionRequest)

GetPresentPositionResponse = _reflection.GeneratedProtocolMessageType('GetPresentPositionResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPRESENTPOSITIONRESPONSE,
  '__module__' : 'akari_proto.joint_controller_pb2'
  # @@protoc_insertion_point(class_scope:akari_proto.GetPresentPositionResponse)
  })
_sym_db.RegisterMessage(GetPresentPositionResponse)

_JOINTCONTROLLERSERVICE = DESCRIPTOR.services_by_name['JointControllerService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETJOINTNAMERESPONSE._serialized_start=80
  _GETJOINTNAMERESPONSE._serialized_end=133
  _GETSERVOENABLEDRESPONSE._serialized_start=135
  _GETSERVOENABLEDRESPONSE._serialized_end=186
  _SETSERVOENABLEDREQUEST._serialized_start=188
  _SETSERVOENABLEDREQUEST._serialized_end=238
  _SETPROFILEACCELERATIONREQUEST._serialized_start=240
  _SETPROFILEACCELERATIONREQUEST._serialized_end=305
  _SETPROFILEVELOCITYREQUEST._serialized_start=307
  _SETPROFILEVELOCITYREQUEST._serialized_end=366
  _SETGOALPOSITIONREQUEST._serialized_start=368
  _SETGOALPOSITIONREQUEST._serialized_end=410
  _GETPRESENTPOSITIONRESPONSE._serialized_start=412
  _GETPRESENTPOSITIONRESPONSE._serialized_end=458
  _JOINTCONTROLLERSERVICE._serialized_start=461
  _JOINTCONTROLLERSERVICE._serialized_end=1068
# @@protoc_insertion_point(module_scope)
