"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import akari_proto.joint_controller_pb2
import google.protobuf.empty_pb2
import grpc

class JointControllerServiceStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    GetJointName: grpc.UnaryUnaryMultiCallable[
        google.protobuf.empty_pb2.Empty,
        akari_proto.joint_controller_pb2.GetJointNameResponse]

    GetServoEnabled: grpc.UnaryUnaryMultiCallable[
        google.protobuf.empty_pb2.Empty,
        akari_proto.joint_controller_pb2.GetServoEnabledResponse]

    SetServoEnabled: grpc.UnaryUnaryMultiCallable[
        akari_proto.joint_controller_pb2.SetServoEnabledRequest,
        google.protobuf.empty_pb2.Empty]

    SetProfileAcceleration: grpc.UnaryUnaryMultiCallable[
        akari_proto.joint_controller_pb2.SetProfileAccelerationRequest,
        google.protobuf.empty_pb2.Empty]

    SetProfileVelocity: grpc.UnaryUnaryMultiCallable[
        akari_proto.joint_controller_pb2.SetProfileVelocityRequest,
        google.protobuf.empty_pb2.Empty]

    SetGoalPosition: grpc.UnaryUnaryMultiCallable[
        akari_proto.joint_controller_pb2.SetGoalPositionRequest,
        google.protobuf.empty_pb2.Empty]

    GetPresentPosition: grpc.UnaryUnaryMultiCallable[
        google.protobuf.empty_pb2.Empty,
        akari_proto.joint_controller_pb2.GetPresentPositionResponse]


class JointControllerServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def GetJointName(self,
        request: google.protobuf.empty_pb2.Empty,
        context: grpc.ServicerContext,
    ) -> akari_proto.joint_controller_pb2.GetJointNameResponse: ...

    @abc.abstractmethod
    def GetServoEnabled(self,
        request: google.protobuf.empty_pb2.Empty,
        context: grpc.ServicerContext,
    ) -> akari_proto.joint_controller_pb2.GetServoEnabledResponse: ...

    @abc.abstractmethod
    def SetServoEnabled(self,
        request: akari_proto.joint_controller_pb2.SetServoEnabledRequest,
        context: grpc.ServicerContext,
    ) -> google.protobuf.empty_pb2.Empty: ...

    @abc.abstractmethod
    def SetProfileAcceleration(self,
        request: akari_proto.joint_controller_pb2.SetProfileAccelerationRequest,
        context: grpc.ServicerContext,
    ) -> google.protobuf.empty_pb2.Empty: ...

    @abc.abstractmethod
    def SetProfileVelocity(self,
        request: akari_proto.joint_controller_pb2.SetProfileVelocityRequest,
        context: grpc.ServicerContext,
    ) -> google.protobuf.empty_pb2.Empty: ...

    @abc.abstractmethod
    def SetGoalPosition(self,
        request: akari_proto.joint_controller_pb2.SetGoalPositionRequest,
        context: grpc.ServicerContext,
    ) -> google.protobuf.empty_pb2.Empty: ...

    @abc.abstractmethod
    def GetPresentPosition(self,
        request: google.protobuf.empty_pb2.Empty,
        context: grpc.ServicerContext,
    ) -> akari_proto.joint_controller_pb2.GetPresentPositionResponse: ...


def add_JointControllerServiceServicer_to_server(servicer: JointControllerServiceServicer, server: grpc.Server) -> None: ...
