# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from akari_proto import joint_controller_pb2 as akari__proto_dot_joint__controller__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class JointControllerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetJointName = channel.unary_unary(
                '/akari_proto.JointControllerService/GetJointName',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=akari__proto_dot_joint__controller__pb2.GetJointNameResponse.FromString,
                )
        self.GetServoEnabled = channel.unary_unary(
                '/akari_proto.JointControllerService/GetServoEnabled',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=akari__proto_dot_joint__controller__pb2.GetServoEnabledResponse.FromString,
                )
        self.SetServoEnabled = channel.unary_unary(
                '/akari_proto.JointControllerService/SetServoEnabled',
                request_serializer=akari__proto_dot_joint__controller__pb2.SetServoEnabledRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SetProfileAcceleration = channel.unary_unary(
                '/akari_proto.JointControllerService/SetProfileAcceleration',
                request_serializer=akari__proto_dot_joint__controller__pb2.SetProfileAccelerationRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SetProfileVelocity = channel.unary_unary(
                '/akari_proto.JointControllerService/SetProfileVelocity',
                request_serializer=akari__proto_dot_joint__controller__pb2.SetProfileVelocityRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SetGoalPosition = channel.unary_unary(
                '/akari_proto.JointControllerService/SetGoalPosition',
                request_serializer=akari__proto_dot_joint__controller__pb2.SetGoalPositionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetPresentPosition = channel.unary_unary(
                '/akari_proto.JointControllerService/GetPresentPosition',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=akari__proto_dot_joint__controller__pb2.GetPresentPositionResponse.FromString,
                )


class JointControllerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetJointName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServoEnabled(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetServoEnabled(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetProfileAcceleration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetProfileVelocity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetGoalPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPresentPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JointControllerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetJointName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJointName,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=akari__proto_dot_joint__controller__pb2.GetJointNameResponse.SerializeToString,
            ),
            'GetServoEnabled': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServoEnabled,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=akari__proto_dot_joint__controller__pb2.GetServoEnabledResponse.SerializeToString,
            ),
            'SetServoEnabled': grpc.unary_unary_rpc_method_handler(
                    servicer.SetServoEnabled,
                    request_deserializer=akari__proto_dot_joint__controller__pb2.SetServoEnabledRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetProfileAcceleration': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProfileAcceleration,
                    request_deserializer=akari__proto_dot_joint__controller__pb2.SetProfileAccelerationRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetProfileVelocity': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProfileVelocity,
                    request_deserializer=akari__proto_dot_joint__controller__pb2.SetProfileVelocityRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetGoalPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.SetGoalPosition,
                    request_deserializer=akari__proto_dot_joint__controller__pb2.SetGoalPositionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetPresentPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPresentPosition,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=akari__proto_dot_joint__controller__pb2.GetPresentPositionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'akari_proto.JointControllerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class JointControllerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetJointName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akari_proto.JointControllerService/GetJointName',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            akari__proto_dot_joint__controller__pb2.GetJointNameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServoEnabled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akari_proto.JointControllerService/GetServoEnabled',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            akari__proto_dot_joint__controller__pb2.GetServoEnabledResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetServoEnabled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akari_proto.JointControllerService/SetServoEnabled',
            akari__proto_dot_joint__controller__pb2.SetServoEnabledRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetProfileAcceleration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akari_proto.JointControllerService/SetProfileAcceleration',
            akari__proto_dot_joint__controller__pb2.SetProfileAccelerationRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetProfileVelocity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akari_proto.JointControllerService/SetProfileVelocity',
            akari__proto_dot_joint__controller__pb2.SetProfileVelocityRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetGoalPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akari_proto.JointControllerService/SetGoalPosition',
            akari__proto_dot_joint__controller__pb2.SetGoalPositionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPresentPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akari_proto.JointControllerService/GetPresentPosition',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            akari__proto_dot_joint__controller__pb2.GetPresentPositionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
