# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from akari_proto import m5_manager_pb2 as akari__proto_dot_m5__manager__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class M5ManagerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetPinOut = channel.unary_unary(
                '/akari_proto.M5ManagerService/SetPinOut',
                request_serializer=akari__proto_dot_m5__manager__pb2.SetPinOutRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.ResetPinOut = channel.unary_unary(
                '/akari_proto.M5ManagerService/ResetPinOut',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SetDisplayColor = channel.unary_unary(
                '/akari_proto.M5ManagerService/SetDisplayColor',
                request_serializer=akari__proto_dot_m5__manager__pb2.SetDisplayColorRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SetDisplayText = channel.unary_unary(
                '/akari_proto.M5ManagerService/SetDisplayText',
                request_serializer=akari__proto_dot_m5__manager__pb2.SetDisplayTextRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SetDisplayImage = channel.unary_unary(
                '/akari_proto.M5ManagerService/SetDisplayImage',
                request_serializer=akari__proto_dot_m5__manager__pb2.SetDisplayImageRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.UseJapaneseFont = channel.unary_unary(
                '/akari_proto.M5ManagerService/UseJapaneseFont',
                request_serializer=akari__proto_dot_m5__manager__pb2.UseJapaneseFontRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.Reset = channel.unary_unary(
                '/akari_proto.M5ManagerService/Reset',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.Get = channel.unary_unary(
                '/akari_proto.M5ManagerService/Get',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=akari__proto_dot_m5__manager__pb2.M5Status.FromString,
                )
        self.GetStream = channel.unary_stream(
                '/akari_proto.M5ManagerService/GetStream',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=akari__proto_dot_m5__manager__pb2.M5Status.FromString,
                )


class M5ManagerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetPinOut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetPinOut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDisplayColor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDisplayText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDisplayImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UseJapaneseFont(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_M5ManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetPinOut': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPinOut,
                    request_deserializer=akari__proto_dot_m5__manager__pb2.SetPinOutRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ResetPinOut': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetPinOut,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetDisplayColor': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDisplayColor,
                    request_deserializer=akari__proto_dot_m5__manager__pb2.SetDisplayColorRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetDisplayText': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDisplayText,
                    request_deserializer=akari__proto_dot_m5__manager__pb2.SetDisplayTextRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetDisplayImage': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDisplayImage,
                    request_deserializer=akari__proto_dot_m5__manager__pb2.SetDisplayImageRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UseJapaneseFont': grpc.unary_unary_rpc_method_handler(
                    servicer.UseJapaneseFont,
                    request_deserializer=akari__proto_dot_m5__manager__pb2.UseJapaneseFontRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=akari__proto_dot_m5__manager__pb2.M5Status.SerializeToString,
            ),
            'GetStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetStream,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=akari__proto_dot_m5__manager__pb2.M5Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'akari_proto.M5ManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class M5ManagerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetPinOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akari_proto.M5ManagerService/SetPinOut',
            akari__proto_dot_m5__manager__pb2.SetPinOutRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResetPinOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akari_proto.M5ManagerService/ResetPinOut',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDisplayColor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akari_proto.M5ManagerService/SetDisplayColor',
            akari__proto_dot_m5__manager__pb2.SetDisplayColorRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDisplayText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akari_proto.M5ManagerService/SetDisplayText',
            akari__proto_dot_m5__manager__pb2.SetDisplayTextRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDisplayImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akari_proto.M5ManagerService/SetDisplayImage',
            akari__proto_dot_m5__manager__pb2.SetDisplayImageRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UseJapaneseFont(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akari_proto.M5ManagerService/UseJapaneseFont',
            akari__proto_dot_m5__manager__pb2.UseJapaneseFontRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akari_proto.M5ManagerService/Reset',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akari_proto.M5ManagerService/Get',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            akari__proto_dot_m5__manager__pb2.M5Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/akari_proto.M5ManagerService/GetStream',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            akari__proto_dot_m5__manager__pb2.M5Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
