// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: akira_proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AkariServiceServiceClient is the client API for AkariServiceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AkariServiceServiceClient interface {
	ListServiceInstances(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListServiceInstancesResponse, error)
	GetServiceInstance(ctx context.Context, in *GetServiceInstanceRequest, opts ...grpc.CallOption) (*ServiceInstance, error)
	LaunchJupyterService(ctx context.Context, in *LaunchJupyterServiceRequest, opts ...grpc.CallOption) (*ServiceInstance, error)
}

type akariServiceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAkariServiceServiceClient(cc grpc.ClientConnInterface) AkariServiceServiceClient {
	return &akariServiceServiceClient{cc}
}

func (c *akariServiceServiceClient) ListServiceInstances(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListServiceInstancesResponse, error) {
	out := new(ListServiceInstancesResponse)
	err := c.cc.Invoke(ctx, "/akira_proto.AkariServiceService/ListServiceInstances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akariServiceServiceClient) GetServiceInstance(ctx context.Context, in *GetServiceInstanceRequest, opts ...grpc.CallOption) (*ServiceInstance, error) {
	out := new(ServiceInstance)
	err := c.cc.Invoke(ctx, "/akira_proto.AkariServiceService/GetServiceInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akariServiceServiceClient) LaunchJupyterService(ctx context.Context, in *LaunchJupyterServiceRequest, opts ...grpc.CallOption) (*ServiceInstance, error) {
	out := new(ServiceInstance)
	err := c.cc.Invoke(ctx, "/akira_proto.AkariServiceService/LaunchJupyterService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AkariServiceServiceServer is the server API for AkariServiceService service.
// All implementations must embed UnimplementedAkariServiceServiceServer
// for forward compatibility
type AkariServiceServiceServer interface {
	ListServiceInstances(context.Context, *emptypb.Empty) (*ListServiceInstancesResponse, error)
	GetServiceInstance(context.Context, *GetServiceInstanceRequest) (*ServiceInstance, error)
	LaunchJupyterService(context.Context, *LaunchJupyterServiceRequest) (*ServiceInstance, error)
	mustEmbedUnimplementedAkariServiceServiceServer()
}

// UnimplementedAkariServiceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAkariServiceServiceServer struct {
}

func (UnimplementedAkariServiceServiceServer) ListServiceInstances(context.Context, *emptypb.Empty) (*ListServiceInstancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServiceInstances not implemented")
}
func (UnimplementedAkariServiceServiceServer) GetServiceInstance(context.Context, *GetServiceInstanceRequest) (*ServiceInstance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceInstance not implemented")
}
func (UnimplementedAkariServiceServiceServer) LaunchJupyterService(context.Context, *LaunchJupyterServiceRequest) (*ServiceInstance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LaunchJupyterService not implemented")
}
func (UnimplementedAkariServiceServiceServer) mustEmbedUnimplementedAkariServiceServiceServer() {}

// UnsafeAkariServiceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AkariServiceServiceServer will
// result in compilation errors.
type UnsafeAkariServiceServiceServer interface {
	mustEmbedUnimplementedAkariServiceServiceServer()
}

func RegisterAkariServiceServiceServer(s grpc.ServiceRegistrar, srv AkariServiceServiceServer) {
	s.RegisterService(&AkariServiceService_ServiceDesc, srv)
}

func _AkariServiceService_ListServiceInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkariServiceServiceServer).ListServiceInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/akira_proto.AkariServiceService/ListServiceInstances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkariServiceServiceServer).ListServiceInstances(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkariServiceService_GetServiceInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkariServiceServiceServer).GetServiceInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/akira_proto.AkariServiceService/GetServiceInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkariServiceServiceServer).GetServiceInstance(ctx, req.(*GetServiceInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkariServiceService_LaunchJupyterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LaunchJupyterServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkariServiceServiceServer).LaunchJupyterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/akira_proto.AkariServiceService/LaunchJupyterService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkariServiceServiceServer).LaunchJupyterService(ctx, req.(*LaunchJupyterServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AkariServiceService_ServiceDesc is the grpc.ServiceDesc for AkariServiceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AkariServiceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "akira_proto.AkariServiceService",
	HandlerType: (*AkariServiceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListServiceInstances",
			Handler:    _AkariServiceService_ListServiceInstances_Handler,
		},
		{
			MethodName: "GetServiceInstance",
			Handler:    _AkariServiceService_GetServiceInstance_Handler,
		},
		{
			MethodName: "LaunchJupyterService",
			Handler:    _AkariServiceService_LaunchJupyterService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "akira_proto/service.proto",
}
