---

- name: Install apt packages
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  become: true

- name: Create keyring directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  become: true

- name: Install keyring
  changed_when: False
  shell:
    curl -fsSL https://download.docker.com/linux/{{ ansible_os_family | lower }}/gpg | gpg --dearmor --batch --yes -o /etc/apt/keyrings/docker.gpg
  become: true

- name: Get architecture
  shell: dpkg --print-architecture
  changed_when: False
  register: host_architecture

- name: Add repository
  apt_repository:
    repo: "deb [arch={{ host_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
  become: true

- name: Set docker version for Ubuntu 
  set_fact:
     docker_version: "{{ docker_version_ubuntu }}"
  when:
    ansible_os_family == "Ubuntu"

- name: Set docker version for Debian
  set_fact:
     docker_version: "{{ docker_version_debian }}"
  when:
    ansible_os_family == "Debian"

- name: Install docker
  apt:
    update_cache: true
    pkg:
      - docker-ce={{ docker_version }}
      - docker-ce-cli={{ docker_version }}
      - containerd.io
      - docker-compose-plugin
    allow_downgrade: true
  become: true
  notify: Restart docker

- name: Add user to docker
  user:
    name: '{{ ansible_env.USER }}'
    groups: docker
    append: yes
  become: true

- name: Add nameserver to /etc/resolv.conf
  lineinfile:
    path: /etc/resolv.conf
    line: "nameserver 8.8.8.8"
    insertafter: EOF
  become: true
  when:
    ansible_os_family == "Debian"