name: Update akira docker images
on:
  workflow_dispatch:

jobs:
  update-akira-image:
    name: Update docker images
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Locate fake files
      run: |
        echo "none" > internal/docker/.docker_credential
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push akira images
      uses: ./.github/actions/build-akira-images
      with:
        compose-path: internal/docker/docker-compose.dev.yml
    - name: Build and push akira-service images
      uses: ./.github/actions/build-akira-images
      with:
        compose-path: internal/akira_services/docker-compose.image.yml
    - name: Post a notification
      run: |
        curl -X POST \
          --data-urlencode 'payload={"text": "<!channel> Published new akira images (commit hash: ${{ github.sha }})"}' \
          ${{ secrets.AKIRA_PUSH_NOTIFICATION_ENDPOINT }}
